### ISSUE TITLE
Normandy-Client 2.0 supporting Action Composition

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/product-delivery#7] opened 2018-08-01 21:42 UTC
_Move this to BZ when we figured out what we want to do here._

This proposal is to change the design of normandy-client from a ridged single task design to a composition based design. 

The current client implements behavior as very specific tasks: 

* show-heartbeat
* preference-experiment
* opt-out-study
* console-log
* preference-rollout
* preference-rollback

As the Normandy has gotten more usage, these actions have been used (abused?) to do things outside of their original intent.  

__For version 2.0 we would__:

1. Implement general recipes (set-pref, install-addon, uninstall-addon, show-heartbeat)
1. Recipes compose a multi-stage job out of those actions. 

__V1 experiments as compositions of V2 composition recipes:__ 

A `preference-experiment` becomes a composition of: 

  1. save-pref-value
  1. set-pref-value <new>
  1. set-pref-value <old>

A `opt-out-study` can be represented as: 

  1. install-addon
  1. update-addon
  1. uninstall-addon

This also lets us ship configuration instead of code!  Getting off the train model greatly increases our agility and ability to _go faster_.  

It'll also empower the Strategy and Insights team to design new experiment types and workflows that are not possible today.  For example, these would all be configuration driven: 

* experiment with survey follow up
* preference-experiment that transitions into a preference-rollout 
* a hotfix does not abuse a `preference-experiment` 

On the more Eng-Ops side it'll also make it easier for us to build user interface and enforce business rules.  It should also make the development process of normandy-client easier as we can clearly define what makes a suitable, general action. ie: small, single purpose, testable, well defined behavior, etc.

**Comment by MattGMoz** [comment] 2018-08-01 23:22
This very much seems like it is heading in the right direction. I don't see "counting" on this list, which was recently discussed.

**Comment by mythmon** [comment] 2018-08-01 23:32
This reminds me a lot of the original vision of the Normandy Driver, which we are [currently moving away from](https://bugzilla.mozilla.org/show_bug.cgi?id=1436129). The original vision of the driver was that there would be a standard set of *capabilities* that Normandy Client provided, via the Normandy Driver. These capabilities included normandy-specific storage, reading and writing preferences, installing add-ons, and heartbeat.

The goal here was that a relatively small set of driver capabilities could be recombined by *actions*, which were Javascript code fetched from the server. The idea was that the driver's capabilities would be heavily scrutinized (ie, by security and Firefox peers), and then actions would be free to do what they liked within the capabilities provided by the driver. This would allow us to update the actions quickly and easily, including making new types of behaviors.

The other goal of the driver model was to allow multiple Normandy clients. Originally this was *the self-repair shim*, a webpage that ran with slightly elevated privileges that could provide some functionality, and *the system add-on*, which would have higher privilege and provide more functionality. The self-repair shim was already available, and easy to adapt to our needs. It provided an extremely easy way to get the project off the ground. The system add-on took much longer to get working, so the self-repair shim was vital to our early success. The system add-on eventually became what today we refer to as The Normandy Client, and the idea of having multiple clients wasn't pursued futher.

As the driver model became less needed, we also saw the way that actions and the driver interacted change. It never really met the original goal of a small set of building blocks that could be recombined. Instead we ended up with new action types requiring entirely new sets of capabilities each time, with very little re-use. There were behaviors needed that couldn't fit in the action/driver model, such as early startup pref setting or detailed interaction with other parts of Firefox, such as was needed for add-ons. Additionally, having code shipped from the server meant we had a compatibility interface to deal with: what if the client and the server had mismatched versions?

Because of the above, actions became little more than glorified function calls. Most of the business logic was encoded directly in Normandy Client, and the actions mostly concerned themselves with version compatibility and boiler plate. They couldn't do much more than set up some state and then call into code on the client to do the real work. So instead we started a project to eliminate the driver, implementing new actions as purely privileged code. The main goals were to reduce code complexity, increasing productivity when writing new actoins, and making testing easier. This project is ongoing.

---

That kind of dodges the question though. It only explains why a similar system didn't work in the past, without really address the proposal: instead of a recipe executing a single action, it could have data for a series of micro-actions that could work in concert to work as building blocks. This is something we considered while designing Normandy originally. I was actually a big fan of it, but we ultimately opted not to do it for a few reasons.

The first was difficulty in designing a set of micro-actions that could be usefully re-used but were also self-contained enough to be written down as simple data. We came to the conclusion that for these units to be small enough to be reusable, they would need a complex set of connections and logic. For example, preference studies would need branching logic to assign a user to one of several possibly values in a study. Rollouts probably wouldn't need such logic, and rollbacks definitely wouldn't. That means that branching logic and preference setting should probably be separate micro-actions. It follows that there is some way to behave conditionally or route data from one microaction to the next.

This strays dangerously close to a full programming language. At least it starts growing beyond what is reasonable to express in JSON. Restricted languages like JEXL or CEL don't have the expressiveness for this either, by design. Our design pushed us to make JavaScript the place where micro-actions were combined together. From this arose the action/driver model explained above.

The second issue is that actions need to have a life outside of recipes. For example, if a study recipe is disabled on the server, the Normandy Client should react by ending the study. But a disabled recipe isn't sent to the client by the server, since that recipe should no longer affect the client. To deal with this, actions have a pre- and post-step. The pre-step runs once before any recipe is run, and the post-step runs once after all recipes have completed. This way the action has the ability to analyze the server state as a whole, and infer an action to take, such as "study X was not seen, so unenroll from X".

If business logic (such as studies should end when a recipe is disabled) is encoded in recipe configuration, then "disabled" recipes would need to be executed on the client. This raises the question of when recipes stop being executed. We can't run all recipes forever, since it would grow to an unreasonable number (about 90% of recipes ever made are currently disabled). However we can't control when a user comes back to us. Perhaps a user opts into a study and then comes back 3 months later (after a summer vacation, for example). That user should still get the correct behavior and be opted out of the study.

We could encode this kind of cleanup into the micro-actions. Each type of micro-action in effect would have a chance to clean up occasionally. This however would mean a different micro-action for different kind of preference setting (rollout vs study). Thus micro-actions become less-reusable and become much more like our current "full" actions: not composable and not re-usable. that brings us back the local-actions model that we are in the process of moving towards.

---

To conclude, I think that while the idea of composing multiple actions together is attractive, it doesn't mesh will with the reality of how Normandy works. The current model of recipes and actions seems to provide better tools to achieve our goals, with the caveat that we still have more work to do to make the actions encompass the full scope of what we want Normandy to do.

Perhaps an even larger re-design of Normandy could solve these problems, and be even more worthy of the version "2.0". I don't think we have the time or resources to do this though. We don't have enough people working on Normandy Client currently to pull it off, and I think it would severely delay other projects we have already committed to even if we did.

Instead I think we should take what we've learned in the last few months, and iterate on our current approach. We should work within our current architecture to achieve our goals. I believe we have the tools to do it, even if they aren't as shiny as they could be. It is often tempting to redesign a project from scratch instead of updating it to fit, but in my experience it is rarely a good idea.

**Closed as completed** 2018-09-27 16:41 UTC
Labels: proposal
